### ISSUE TITLE
First time: only power device created

### ISSUE THREAD

**Issue by mvdw** [galadril/Domoticz-AWTRIX3-Plugin#1]
Thanks for creating this plugin - it is just what I needed!
This is my attempt to try to help improving this plugin:

The first time I added the hardware "Awtrix" in Domoticz, only the "Awtrix - Power" device was created.
And some errors appeared in the log, if I remember well (but I could not register them).

Later, I changed the hardware and saved again - this time, also the other devices were created.

I am still investigating how this all works.
Anyhow, in the "plugin.py", I see the following:

~~~
    def create_devices(self):
        if self.power_unit not in Devices:
            Domoticz.Device(Name="Power", Unit=self.power_unit, TypeName="Switch").Create()
            Domoticz.Log("Power Device created.")
            self.send_notify_device("Domoticz")
~~~

This function is not defined anywhere: "send_notify_device" - so I think that is the cause of the problem.

If execution stopped here, then this caused me to end up with only the power device, and not the others.
And during the second execution, this "if" is skipped, which created the other devices.
Maybe it should be changed into a call to "send_notify_message"?

**Comment by galadril** [comment]
mm thanks for the clear explanation, should be fixed in the latest version now!

**Comment by mvdw** [comment]
OK
