### ISSUE TITLE
Various problems in dzvents-sample.txt

### ISSUE THREAD

**Issue by mvdw** [galadril/Domoticz-AWTRIX3-Plugin#2]
I have been modifying the "dzvents-sample.txt" script to make it work....

The problems I solved: 
- The devices were updated in random sequence, so I modified the data structure of devicesConfig and used ipairs to loop them.
- The device names were not the ones I have in my system (AWTRIX3 replaced by Awtrix).
- Adapted the devicesConfig to my devices - you can ignore this.
- Adapted the logging to STATUS - so that I can see what was sent.
- Corrected the currentIndex - the first index is 1 in Lua, not 0.

This is the result: 
[UlanziClock.lua.txt](https://github.com/user-attachments/files/18148491/UlanziClock.lua.txt)

It works fine if I replace line 135 by:
~~~
local appDevice = domoticz.devices('Awtrix - Send Notification')
~~~

However, if I use this like in your latest change from a few days before:
~~~
local appDevice = domoticz.devices('Awtrix - Send Custom App')
~~~
Then I get almost the same behaviour.
The different "apps" do never appear together on the display - only the last sent one.

I think this is due to the lack of the query parameter name=appname in the URL of the http request.
As described in [the API documentation](https://blueforcer.github.io/awtrix3/#/api?id=interaction).
The display treats all the "apps" we send it as the same app, since it receives no name.

This is the main problem I want to report here.

I do not see a simple solution here...

**Comment by galadril** [comment]
Yeah currently in my sample im putting a status on the custom app, and not using notifications because they are only there for a couple of seconds.

and indeed its posting a status on 1 specific custom app called Domoticz, so only 1 status is available, but you could create a json with multiple text/icon combinations.. which would actually act the same as multiple apps


![image](https://github.com/user-attachments/assets/b6dd6edf-75fa-4e80-b49a-67c31677a18b)

I have not tested this yet (im not able today), but i guess you could send the next message to actually create multiple apps

```
[
  {"text":"1", "icon":123},
  {"text":"2", "icon":123}
]
```

**Comment by galadril** [comment]
so the plugin allows for all these things, any my dzvents script was just a sample to show how to use it. 
We could add more samples with notifications/ multi app setup/etc

**Comment by galadril** [comment]
i could add another push button to toggle apps left and right... could be handy as well

**Comment by mvdw** [comment]
I tryed the multi-app solution, but it does not seem to work.
The display shows the default icon, and then the complete JSON text as in the description field.

[UlanziClock-3.dz.txt](https://github.com/user-attachments/files/18155579/UlanziClock-3.dz.txt)

The Domoticz log says:

~~~
Sent Custom App data with default icon: 39762 | message: [ { "text": "On", "icon": 4889 }, { "text": "20.0°C", "icon": 2355 }, { "text": "563W", "icon": 95 }, { "text": "381L", "icon": 18191 }, { "text": "9.5°C", "icon": 64162 }, { "text": "2.46 m³", "icon": 54633 } ]
~~~


Any idea what is going wrong?

**Comment by galadril** [comment]
maybe that api call is not implemented in awtrix but only in MQTT..
_EDIT: it works, i just send a multi app message via postman:_

```
curl --location 'http://192.168.1.122/api/custom' \
--header 'accept: */*' \
--header 'Authorization: Basic XXX=' \
--header 'Content-Type: application/json' \
--data '[
  {"text":"Test1", "icon": 39762},
  {"text":"Test2", "icon": 39762}
]'
```

**Comment by galadril** [comment]
As they are then custom apps, you neem to rotate between the values yourself via the left and right buttons

**Comment by galadril** [comment]
Updated the plugin to 0.0.4 with small fix

**Comment by galadril** [comment]
Created a new version with v0.0.4 with new buttons to toggle next and previous app.
Also reworked the samples a bit

**Comment by mvdw** [comment]
Nice - the new buttons work good.

The multiple apps version of my code listed above now also works!

Thank you very much

**Comment by galadril** [comment]
Great thanks
