### ISSUE TITLE
Much more pushbuttons for changing AWTRIX3 settings?

### ISSUE THREAD

**Issue by joro75** [galadril/Domoticz-AWTRIX3-Plugin#7]
I recently added the possibility to change the general settings of the AWTRIX3 firmware. 
This does allow to change some settings, by specifying the correct JSON commands in the description of the pushbutton and then activate the action. This is however not very user friendly, cumbersome and could be further simplified.

It is now for example also relatively easy to add:
* Switch for showing/hiding the internal AWTRIX humidity sensor app
* Switch for showing/hiding the internal AWTRIX temperature sensor app
* Switch for showing/hiding the internal AWTRIX battery level app
* Selector for showing/hiding the weekday indication on the internal time app
* Selector for selecting the color of the global text
* Selector for selecting a global overlay (nice to show extreme weather conditions)
* Slider for the brightness
* Selector for selecting the transition effect
* and so on....

The advantage will be that more effects and customizations can be easily selected by Domoticz users. The disadvantage can be that a lot of devices will be generated.

What is your idea on this? I am able to implement a lot of this, and can also test/verify all of those devices.

**Comment by galadril** [comment]
Sounds good. Was wondering myself if all these settings are actually needed in Domoticz. But indeed this seems better then a json via the description

**Comment by galadril** [comment]
Maybe a subset of devices? Like brightness etc, that could be hand in Domoticz?

I guess switches to turn apps on an off are less interresting?

**Comment by joro75** [comment]
I have created some additional controls (see: #8) to change the most obvious settings. Adding even more controls for the other settings is indeed not necessary at this moment.

**Comment by galadril** [comment]
Thanks.. btw i added a nice new dzvents sample script to set the overlay based on the weather forecast ;) 

https://github.com/galadril/Domoticz-AWTRIX3-Plugin/blob/master/samples/dzvents-weather-overlay-sample.txt

**Comment by galadril** [comment]
Btw i've checked with Blueforcer and we can add domoticz scripts here as flows
https://flows.blueforcer.de/search?provider=domoticz

**Comment by joro75** [comment]
Nice! 👍 I do know that AWTRIX3 has a site to showcase all the flows. Nice that Domoticz is now also present with some flows!
